### ISSUE TITLE
[3pt]  - Display comments for a given item on the Comments pop-up - Student B

### ISSUE THREAD

**Issue by uisendy** [uisendy/Meal-webApp#11]
When the popup loads, the webapp retrieves data from the [Involvement API](https://www.notion.so/microverse/Involvement-API-869e60b5ad104603aa6db59e08150270) to show the item comments.

<img width="465" alt="Screenshot 2021-06-27 at 22 21 00" src="https://user-images.githubusercontent.com/7466903/123558341-f8406200-d795-11eb-9074-9a6e2b6a7ec8.png">

This task **does not** include the counter of the comments.

**Comment by SurafelGetachewT** [comment]
When the popup loads, the web app retrieves data from the Involvement API.
![image](https://user-images.githubusercontent.com/39293404/187622682-07046379-09d6-4a78-8a5f-76968e3fb892.png)

**Comment by uisendy** [comment]
[SurafelGetachewT](https://github.com/SurafelGetachewT) 👏🏾 👏🏾 

Task Completed and neatly. 

Design is Good as well as the General work itself. Great Job.

1. JavaScript Best practices used. 
2. Best CSS and HTML Practices
3. Good Handling using ES6
4. Module utilization is Good.
