### ISSUE TITLE
[4pt]  - Display number of likes for each item on the Homepage - Student A

### ISSUE THREAD

**Issue by uisendy** [uisendy/Meal-webApp#12]
When the page loads, the webapp the [Involvement API](https://www.notion.so/microverse/Involvement-API-869e60b5ad104603aa6db59e08150270) to show the item likes and combines them with the data from the base API.

Remember that your page should make only 2 requests:
- one to the base API
- and **one** to the Involvement API.

This task **does not** include displaying the likes button (heart icon on the wireframe) for each item.

**Comment by uisendy** [comment]
**When the page Loads, the page loads the number of likes from each meal and updates the DOM with the total number of Likes.** 

**The page makes request from** 

- The involvement API for the number of Likes for Each meal and 
- The Mead-db API for the Image, The category, and the number of category, and the Name of the Meal. 

The preview is as show below. 
![image](https://user-images.githubusercontent.com/95294594/188055118-ce828f77-1130-4ff2-bed7-c3a3034d1b00.png)

**Comment by SurafelGetachewT** [comment]
Hi @uisendy 

Your project is complete! There is nothing else to say other than

![2](https://user-images.githubusercontent.com/39293404/188132814-0e56237c-66cb-465a-b71f-b825321854af.gif)
