### ISSUE TITLE
[4pt]  - Display list of items on the Homepage - Student A

### ISSUE THREAD

**Issue by uisendy** [uisendy/Meal-webApp#15]
Create the main part of the homepage that keeps the layout from the wireframe: 

<img width="521" alt="Screenshot 2021-06-27 at 21 50 23" src="https://user-images.githubusercontent.com/7466903/123557585-f1afeb80-d791-11eb-96ae-17be082e9359.png">

When the page loads, the webapp retrieves data from  the selected API and shows the list of items on screen with the basic data (e.g. title + image).

Prepare also "Comments" and "Reservations" buttons. They should be doing nothing - just being displayed.

This task **does not** include displaying the number of likes for each item.

This task **does not** include the counter of the items.

**Comment by SurafelGetachewT** [comment]
We have created the main part of the homepage that keeps the layout from the wireframe:

1. When the page loads, the web app retrieves data from the Meal-DB API and shows the list of Meals on the screen with the basic data (title + image).

![image](https://user-images.githubusercontent.com/39293404/187607184-771ceb6f-4061-45c4-8da6-df870d053cfd.png)

2. We have also Prepared the "Comments" buttons. They have done nothing - just being displayed.

**Comment by uisendy** [comment]
List of Items has been fully updated, Comments and likes updated as well.

**Comment by SurafelGetachewT** [comment]
Hello @uisendy ,

You have successfully updated LIst of items Comments, and Likes, 
![1](https://user-images.githubusercontent.com/39293404/188132576-17b09a62-9b09-447d-ad68-8efb626b46b1.gif)

You did great.
