### ISSUE TITLE
[0.5pt] Add footer - group task

### ISSUE THREAD

**Issue by uisendy** [uisendy/Meal-webApp#16]
Create footer according to the wireframe: 

<img width="551" alt="Screenshot 2021-06-27 at 21 42 29" src="https://user-images.githubusercontent.com/7466903/123557345-c082eb80-d790-11eb-969a-2fc82bbec349.png">

**Comment by SurafelGetachewT** [comment]
The Page footer is successfully created based on the wireframe guideline.

**Comment by uisendy** [comment]
[SurafelGetachewT](https://github.com/SurafelGetachewT) 👏🏾 👏🏾 

Task Completed and neatly. 

Design is Good as well as the General work itself. Great Job.

1. JavaScript Best practices used. 
2. Best CSS and HTML Practices
3. Good Handling using ES6
4. Module utilization is Good.
