### ISSUE TITLE
[3pt]  - Add tests for comments counter - Student B

### ISSUE THREAD

**Issue by uisendy** [uisendy/Meal-webApp#2]
Make sure that function for the comments counter is covered with unit tests using Jest.

**Comment by SurafelGetachewT** [comment]
We have created a commentCouter.test.js file and we can cover it with a unit test using jest.

![image](https://user-images.githubusercontent.com/39293404/187950097-d400ab5c-153f-46c2-8fa6-dddc9aa5b6a8.png)

**Comment by uisendy** [comment]
Hello @[SurafelGetachewT](https://github.com/SurafelGetachewT) SurafelGetachewT, my Good partner 

The test cases and test was reviewed and Quality is Excellent and the App passed the test 

Kudos: 👏🏾
