### ISSUE TITLE
[3pt]  - Add tests for items counter - Student A

### ISSUE THREAD

**Issue by uisendy** [uisendy/Meal-webApp#3]
Make sure that function for the items counter is covered with unit tests using Jest.

**Comment by uisendy** [comment]
Test file was added, configure and All test cases have passed. Task Completed

![image](https://user-images.githubusercontent.com/95294594/188129390-e8b157b1-4518-424f-885b-18dd3b622e3f.png)

**Comment by SurafelGetachewT** [comment]
Hello @uisendy,

You have tested the project successfully, that is Great job
![1](https://user-images.githubusercontent.com/39293404/188137697-f44b0b7e-67c2-4d61-ae37-701c0d070a21.gif)
