### ISSUE TITLE
[3pt]  - Add comments counter - Student B

### ISSUE THREAD

**Issue by uisendy** [uisendy/Meal-webApp#5]
Even if the API gives you the number of comments you will create a specific function to calculate it.

Make sure that the correct number is displayed on the Comments pop up.

**Comment by SurafelGetachewT** [comment]
Create a specific function to calculate the number of comments.
 Display The number of comments on the Comments pop-up.
![image](https://user-images.githubusercontent.com/39293404/187630047-cc8b5f61-8f8e-4af1-809c-5848eb39dc45.png)

**Comment by uisendy** [comment]
Good Work so far [SurafelGetachewT](https://github.com/SurafelGetachewT) 🚀 🚀 

This is a very good achievement and milestone is completed. 

Kudos 👍🏾
