### ISSUE TITLE
[3pt]  - Add all items counter on the Homepage - Student A

### ISSUE THREAD

**Issue by uisendy** [uisendy/Meal-webApp#6]
Even if the API gives you the number of items, you will create a specific function to calculate it.

Make sure that the correct number is displayed on the Homepgae.

**Comment by uisendy** [comment]
Add all item counter on the homepage was done and created by doing the following, 

1. Creating a function to calculate the items obtained from the API using the .length method for calulating the number of items in a array. 
2. The Items was dynamically displayed on the DOM for each meal and the number of category. 

The Preview is as indicated below. 

the the particular meal - beef
![image](https://user-images.githubusercontent.com/95294594/188055853-aaf24ca1-142f-497f-be1b-531b676faa9f.png)

and for the total category
![image](https://user-images.githubusercontent.com/95294594/188055958-fa9d4c88-ea6a-468e-89fd-33a94b8a5232.png)
![image](https://user-images.githubusercontent.com/95294594/188056071-839bc95c-8163-4dc0-9034-8d727d1276b4.png)

**Comment by SurafelGetachewT** [comment]
Hello @uisendy ,

You made our project complete, You did great here
![1](https://user-images.githubusercontent.com/39293404/188135981-e5f83c2c-067a-4b36-90f2-87db6ca1a77b.gif)
