### ISSUE TITLE
[4pt]  - Create feature: add new comment - Student B

### ISSUE THREAD

**Issue by uisendy** [uisendy/Meal-webApp#8]
Implement the "add new comment" form on the Comments pop up according to the wireframe:

<img width="360" alt="Screenshot 2021-06-27 at 22 32 36" src="https://user-images.githubusercontent.com/7466903/123558625-98e35180-d797-11eb-9607-8f294273ca01.png">

When the user clicks on the "Comment" button, the data is recorded in the [Involvement API](https://www.notion.so/microverse/Involvement-API-869e60b5ad104603aa6db59e08150270) and the screen is updated.

**Comment by SurafelGetachewT** [comment]
Implement the "add new comment" form on the Comments pop-up according to the wireframe:
![image](https://user-images.githubusercontent.com/39293404/187624174-4ec7f4ae-dfff-4554-ac13-8774ea6f620a.png).
When the user clicks on the "Comment" button, the data is recorded in the Involvement API and the screen is updated.
![image](https://user-images.githubusercontent.com/39293404/187624400-1a9668b6-dc28-4a9d-b741-8dd383c31d29.png)

**Comment by uisendy** [comment]
Awesome Work so far [SurafelGetachewT](https://github.com/SurafelGetachewT)

Design is Good as well as the General work itself. Great Job.

1. JavaScript Best practices used. 
2. Best CSS and HTML Practices
3. Good Handling using ES6
4. Module utilization is Good.
