### ISSUE TITLE
[3pt]  - Create feature: add  new like - Student A

### ISSUE THREAD

**Issue by uisendy** [uisendy/Meal-webApp#9]
When the user clicks on the Like button of an item (on Homepage), the interaction is recorded in the Involvement API and the screen is updated.

**Comment by uisendy** [comment]
This feature was created by creating a POST method request to the Involvement API to update the API and also create a function to instantly update the State of The DOM until refresh of windows.

**Comment by SurafelGetachewT** [comment]
Hi @uisendy 

You have done great by creating a POST method request to the involvement API.

![2](https://user-images.githubusercontent.com/39293404/188133719-3952d93e-14b8-4b77-a06f-5677b9ecb76e.gif)

Happy coding
